name: segyio_pylops
channels:
  - defaults
  - conda-forge
  - numba
dependencies:
  - python>=3.6.4
  - numpy>=1.15.0
  - scipy
  - pyfftw
  - pylops
  - matplotlib
  - ipython
  - jupyter
  - numba
  - icc_rt
  - pip:
    - segyio
